# Setup
title:        Hiếu giề's blog
tagline:      Something need to share for you
baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author:
  name:       Hiếu Giề
  url:        http://hieugie.info

#Others
markdown: HieuGie